// Generated by ChileQi JSON Class Generator
// QQ：1628983882

package yh.app.model;

public class TianJiaHaoYouHuiKuiModel
{

	public class Content
	{
		private String code;
		private String fqr;
		private String fqrname;
		private String fssj;
		private String id;
		private String isreceive;
		private String jsr;
		private String message;
		private String sfty;
		private String ticket;
		private String title;

		public String getCode()
		{
			return code;
		}

		public void setCode(String code)
		{
			this.code = code;
		}

		public String getFqr()
		{
			return fqr;
		}

		public void setFqr(String fqr)
		{
			this.fqr = fqr;
		}

		public String getFqrname()
		{
			return fqrname;
		}

		public void setFqrname(String fqrname)
		{
			this.fqrname = fqrname;
		}

		public String getFssj()
		{
			return fssj;
		}

		public void setFssj(String fssj)
		{
			this.fssj = fssj;
		}

		public String getId()
		{
			return id;
		}

		public void setId(String id)
		{
			this.id = id;
		}

		public String getIsreceive()
		{
			return isreceive;
		}

		public void setIsreceive(String isreceive)
		{
			this.isreceive = isreceive;
		}

		public String getJsr()
		{
			return jsr;
		}

		public void setJsr(String jsr)
		{
			this.jsr = jsr;
		}

		public String getMessage()
		{
			return message;
		}

		public void setMessage(String message)
		{
			this.message = message;
		}

		public String getSfty()
		{
			return sfty;
		}

		public void setSfty(String sfty)
		{
			this.sfty = sfty;
		}

		public String getTicket()
		{
			return ticket;
		}

		public void setTicket(String ticket)
		{
			this.ticket = ticket;
		}

		public String getTitle()
		{
			return title;
		}

		public void setTitle(String title)
		{
			this.title = title;
		}
	}

	private String code;
	private Content content;
	private String message;
	private String time;

	public String getCode()
	{
		return code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public Content getContent()
	{
		return content;
	}

	public void setContent(Content content)
	{
		this.content = content;
	}

	public String getMessage()
	{
		return message;
	}

	public void setMessage(String message)
	{
		this.message = message;
	}

	public String getTime()
	{
		return time;
	}

	public void setTime(String time)
	{
		this.time = time;
	}

}
